#!/usr/bin/env sh
#YABAI STUFF

# bsp or float (default: bsp)
#yabai -m config layout bsp

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Stats$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotlight$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
#yabai -m rule --add app="Fantastical" manage=off
#yabai -m rule --add app="^Spotify$" manage=off
#yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off


# allocating spaces to apps
#browser
yabai -m rule --add app="^Safari$" space=2

#terminal and document viewers
yabai -m rule --add app="^(iTerm2|Skim|Preview)$" space=1

# Messagges and Whatsapp
yabai -m rule --add app="^(WhatsApp|Messages)$" space=3

# Spotify
yabai -m rule --add app="^Spotify$" space=4


## Some random global settings
yabai -m config focus_follows_mouse          autoraise
yabai -m config focus_follows_mouse          on

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
#yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity        0.97
#yabai -m config window_border                on | off

## WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
yabai -m config window_border off

## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
#yabai -m config window_border on
#yabai -m config window_border_width 3
#yabai -m config active_window_border_color 0xFF40FF00
#yabai -m config normal_window_border_color 0x00FFFFFF
#yabai -m config insert_feedback_color        0xffd75f5f

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
#yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
#yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
#yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

#Limelight addon (Kill it and start it each time Yabai starts)
#yabai -m signal --add event=application_activated action="pkill -SIGUSR1 limelight &> /dev/null"

#killall limelight &>/dev/null
#limelight &

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash /Users/asito/CustomScripts/SwitchSpaces/window-focus-on-destroy.sh"
# yabai -m signal --add event=space_changed action="export CUR_ACTIVE_APP=\"iTerm2\""

echo "yabai configuration loaded.."

#END
